version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: pg-care
    environment:
      POSTGRES_USER: care
      POSTGRES_PASSWORD: carepass
      POSTGRES_DB: caredb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U care -d caredb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: {}
