services:
  backend:
    build: ./backend
    container_name: backend_dcare
    networks:
      - dcare_network
    hostname: backend_dcare
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - dcare_network
    env_file:
      - .env.docker
    ports:
      - "5173:8080"
    depends_on:
      - backend

  postgres:
    image: postgis/postgis:16-3.4
    container_name: pg-care
    env_file:
      - .env.docker
    # Note: The variables below are also set from your .env.docker file.
    # This environment section is only needed if you want to override them
    # or if they aren't in the env_file.
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5433:5432"
    networks:
      - dcare_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PG_USER} -d $${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

# Top-level declaration for the named volume
volumes:
  pgdata:

# Top-level declaration for the network
networks:
  dcare_network:
    driver: bridge